# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # basic pre-commit checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: TransformMNIST.ipynb
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict

  # further simple fast checks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations
      - id: python-no-log-warn
      - id: python-check-blanket-noqa

  # remove unused imports and variables in standard library
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        language: python

  # sort imports according to PEP8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  # static type hint checks
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy

  # automatic upgrade syntax to newer versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade

  # black code formatting
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9

  # PEP8 style enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [ "--max-line-length=88", "--ignore=E203, W503" ]

  # clean notebook
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  # notebook hooks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-check-ast
      - id: nbqa-isort
      # enable if required
      # - id: nbqa-mypy
      #   args: [ "--ignore-missing-imports" ]
      - id: nbqa-pyupgrade
      - id: nbqa-black
        language_version: python3.9
      - id: nbqa-flake8
        # remove E731 if possible
        args: [ "--max-line-length=88",  "--ignore=E203,W503,E731" ]
